name: release
on: 
  schedule:
    - cron: '00 01,13 * * *'
  workflow_dispatch:

env:
  TWINE_PASSWORD: ${{ secrets.PYPI_PASS }}
  TWINE_USERNAME: ${{ secrets.PYPI_USER }}
  ANACONDA_API_TOKEN: ${{ secrets.ANACONDA_TOKEN }}

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
    - run: pip install -e ".[dev]"
    - run: conda install conda-build
    - run: ./action.sh
