name: release
schedule:
    - cron: '00 01,13 * * *'
  workflow_dispatch: #allows you to trigger manually

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
    - run: ./action.sh
