name: release
on: 
  schedule:
    - cron: '00 01,13 * * *'
  workflow_dispatch:

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
    - run: pip install -e ".[dev]"
    - run: ./action.sh
