name: release
on: 
  schedule:
    - cron: '00 01,13 * * *'
  workflow_dispatch:

env:
  TWINE_PASSWORD: ${{ secrets.PYPI_PASS }}
  TWINE_USERNAME: ${{ secrets.PYPI_USER }}
  ANACONDA_API_TOKEN: ${{ secrets.ANACONDA_TOKEN }}

jobs:
  release:
    strategy:
      matrix:
        lib: [stdlib, numpy, pandas, pytorch]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
    - name: setup conda
      run: |
        wget https://raw.githubusercontent.com/fastai/fastsetup/master/setup-conda.sh
        chmod u+x setup-conda.sh
        ./setup-conda.sh
    - uses: fastai/workflows/conda-env@master
    - name: install dependencies
      run: | 
        conda install -qy mamba
        mamba install -qy anaconda-client conda-build wheel setuptools
        pip install -Uqq twine sphinx fastcore pip wheel fastrelease
    - name: parse data & release if appropriate
      run: ./action.sh ${{ matrix.lib }}

