name: release
on: 
  schedule:
    - cron: '00 01,13 * * *'
  workflow_dispatch:

env:
  TWINE_PASSWORD: ${{ secrets.PYPI_PASS }}
  TWINE_USERNAME: ${{ secrets.PYPI_USER }}
  ANACONDA_API_TOKEN: ${{ secrets.ANACONDA_TOKEN }}

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
    - name: setup conda
      run: |
        wget https://raw.githubusercontent.com/fastai/fastsetup/master/setup-conda.sh
        ./setup-conda.sh
        conda install conda-build
    - name: install dependencies
      run: | 
        pip install -U twine
        pip install -e ".[dev]"
    - name: parse data & release if appropriate
      run: ./action.sh
